### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sheijk** [ocamllabs/compiler-hacking#2]
On [this page](https://github.com/ocamllabs/compiler-hacking/wiki/Value-specifications-in-structures) there is a broken link to http://caml.inria.fr/pub/docs/manual-ocaml/manual021.html#toc70. This should probably point to [here](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec213) now.

**Comment by yallop** [comment]
Fixed; thanks!
