### ISSUE TITLE
Document New Printexc values

### ISSUE THREAD

**Issue by dsheets** [ocamllabs/compiler-hacking#6]
`Printexc.get_raw_backtrace` in particular is new but is not marked as such in the ocamldoc at http://caml.inria.fr/pub/docs/manual-ocaml/libref/Printexc.html.

**Comment by yallop** [comment]
Added to the [list of things to work on](https://github.com/ocamllabs/compiler-hacking/wiki/Things-to-work-on#document-new-printexc-values).
