### ISSUE TITLE
Compelling use case for wildcard recursive binding

### ISSUE THREAD

**Issue by objmagic** [ocamllabs/compiler-hacking#9]
Hi, 

I would like to know what compiling use case for wildcard recursive binding are in [this task](https://github.com/ocamllabs/compiler-hacking/wiki/Things-to-work-on#allow-recursive-bindings-with-_). I feel like convincing others this feature is useful is important. 

cc mentor of this task @lpw25 ?

**Comment by lpw25** [comment]
There is not really a compelling use case, the feature is more about improving the consistency of the language. In general, you can use "_" anywhere where you could use a variable pattern. This is one of the few exceptions and so it would be nice to allow it.
